# Generated by Django 5.1.7 on 2025-03-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='default_profile_img.jpg', null=True, upload_to='avatars/'),
        ),
    ]
